title: Детские Страшилки
description: Коллекция детских рассказов-страшилок на русском языке
# baseurl: "/kids-horror-stories-ru"
# url: "https://alexeygrigorev.github.io"
permalink: /:title/

collections:
  stories:
    output: true
    permalink: /stories/:path/

defaults:
  - scope:
      path: ""
      type: "stories"
    values:
      layout: "story"

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

sass:
  style: compressed

podcast:
  url: "https://alexeygrigorev.com/kids-horror-stories-ru"
  author: "Alexey Grigorev"
  email: "alexey.s.grigoriev@gmail.com"
  title: "Детские Страшилки"
  description: "Аркаша и его папа фотографируют разные предметы и создают страшные и захватывающие истории на основе этих фотографий"
  spotify: "https://open.spotify.com/show/3vo7Q3MiEgw9ZeZBU2iDGr"