name: Process Stories

on:
  schedule:
    # - cron: '*/15 * * * *'  # Runs every 15 minutes
    # - cron: '0 * * * *'  # Runs every hour
    - cron: '0 0 * * *' # Runs every day
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  process-stories:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install uv
        uv sync

    - name: Run process_stories.py
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-1'
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        S3_BUCKET_IMAGES: 'kids-horror-stories-ru-images'
      run: |
        uv run python process_stories.py

    - name: Commit changes
      run: |
        EPISODE_NAME=$(ls -t _stories/*.md | head -1)
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "$EPISODE_NAME" || echo "No changes to commit"
        git push
